---
- name: Check if ffmpeg is already installed
  stat:
    path: "{{ ffmpeg_executable_path }}"
  register: ffmpeg_bin

- name: Check if ffprobe is already installed
  stat:
    path: "{{ ffprobe_executable_path }}"
  register: ffprobe_bin

- name: Create a temp directory
  file:
    path: "{{ ffmpeg_temp_path }}"
    state: directory
  when: (not ffmpeg_bin.stat.exists) or
        (not ffprobe_bin.stat.exists)

- name: Download from custom source
  get_url:
    url: https://johnvansickle.com/ffmpeg/builds/ffmpeg-git-amd64-static.tar.xz
    dest: "{{ ffmpeg_temp_path }}/ffmpeg-git-amd64-static.tar.xz"
  when: (not ffmpeg_bin.stat.exists) or
        (not ffprobe_bin.stat.exists)

- name: Unarchive to temp directory
  shell: tar xf {{ ffmpeg_temp_path }}/ffmpeg-git-amd64-static.tar.xz --strip-components=1 -C {{ ffmpeg_temp_path }}/
  when: (not ffmpeg_bin.stat.exists) or
        (not ffprobe_bin.stat.exists)

- name: Move ffmpeg to executables directory
  command: mv {{ ffmpeg_temp_path }}/ffmpeg {{ ffmpeg_executable_path }}
  args:
    creates: "{{ ffmpeg_executable_path }}"

- name: Move ffprobe to executables directory
  command: mv {{ ffmpeg_temp_path }}/ffprobe {{ ffprobe_executable_path }}
  args:
    creates: "{{ ffprobe_executable_path }}"

- name: Make ffmpeg executable by all users
  file:
    path: "{{ ffmpeg_executable_path }}"
    mode: 0755
  when: not ffmpeg_bin.stat.exists

- name: Make ffprobe executable by all users
  file:
    path: "{{ ffprobe_executable_path }}"
    mode: 0755
  when: not ffprobe_bin.stat.exists

- name: Delete temp directory
  file:
    path: "{{ ffmpeg_temp_path }}"
    state: absent
